spring:
  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  sharding-sphere:
    # 连接池
    datasource:
      names: master,blog-shard-0,blog-shard-1
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/personal_blog_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: houyanjun
        password: 123456
      blog-shard-0:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/personal_blog_db_0?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: houyanjun
        password: 123456
      blog-shard-1:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/personal_blog_db_1?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: houyanjun
        password: 123456
    props:
      sql:
        show: true
    sharding:
      # 设置默认库
      default-data-source-name: master
      tables:
        # 自定义user分库分表规则
        user_info:
          # 实际数据节点 可以用逗号隔开多个库表配置
          actual-data-nodes: blog-shard-$->{0..1}.user_info_$->{0..2},
          # 表策略
          tableStrategy:
            inline:
              # sharding字段
              shardingColumn: id
              # 采用算法-表
              algorithmExpression: user_info_$->{id % 3}
          keyGenerator:
            column: id
            type: SNOWFLAKE
      # 默认数据库分库规则
      default-database-strategy:
        inline:
          # 采用算法-库
          algorithm-expression: blog-shard-$->{id % 2}
          # 使用字段进行计算
          sharding-column: id

management:
  health:
    db:
      enabled: false


# mybatis-plus 配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:**/*Mapper.xml
  global-config:
    db-config:
      # 1 代表已删除，不配置默认是1，也可修改配置
      logic-delete-value: 1
      # 0 代表未删除，不配置默认是0，也可修改配置
      logic-not-delete-value: 0
      # 添加非空判断
      update-strategy: not_empty
      insert-strategy: not_empty
  # 日志配置
configuration:
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  map-underscore-to-camel-case: true # 开启驼峰映射
  cache-enabled: false # 全局关闭二级缓存
  call-setters-on-nulls: true
